const KNOWLEDGE_KEY = 'blizzard_racing_icicle_knowledge';

const defaultKnowledge = `Team Name: Blizzard Racing
Team Manager: Shriv
Goal: Win the F1 in Schools UK National Finals.
Core Values: Innovation, Teamwork, Perseverance.
Sponsors: Seeking sponsors for 2024 season. Focus on local engineering firms.
`;

export const icicleService = {
  getKnowledge: (): string => {
    return localStorage.getItem(KNOWLEDGE_KEY) ?? defaultKnowledge;
  },
  saveKnowledge: (knowledge: string) => {
    localStorage.setItem(KNOWLEDGE_KEY, knowledge);
  },
  query: (question: string): string => {
      const knowledge = icicleService.getKnowledge().toLowerCase();
      const q = question.toLowerCase();

      // Physics knowledge
      if (q.includes('drag')) {
          return "Drag is the resistive force an object experiences when moving through a fluid (like air). In F1 in Schools, minimizing drag is crucial for top speed. Key factors are frontal area (streamlining) and surface finish.";
      }
      if (q.includes('downforce') || q.includes('lift')) {
          return "Downforce is negative lift, an aerodynamic force that presses the car onto the track. It increases grip for better cornering. It's generated by wings and the car's body shape, often at the cost of increased drag.";
      }
      if (q.includes('bernoulli')) {
          return "Bernoulli's principle states that an increase in the speed of a fluid occurs simultaneously with a decrease in pressure. This is the fundamental principle behind how wings generate lift (or downforce). Faster air over a surface creates lower pressure compared to the slower air underneath.";
      }
       if (q.includes('laminar flow')) {
          return "Laminar flow is smooth, streamlined airflow with minimal turbulence. Maintaining laminar flow over the car body for as long as possible is key to reducing drag. Abrupt changes in shape can cause the flow to become turbulent, which increases drag significantly.";
      }
      if (q.includes("newton's first law") || q.includes('inertia')) {
          return "Newton's First Law, the law of inertia, states that an object in motion stays in motion with the same speed and in the same direction unless acted upon by an unbalanced force. For our car, this means it will keep moving in a straight line until forces like drag, friction, or turning forces change its motion.";
      }
      if (q.includes("newton's second law") || q.includes('f=ma')) {
          return "Newton's Second Law of Motion is F=ma (Force = mass × acceleration). This is fundamental to our car's performance. The thrust from the CO2 canister (Force) accelerates the car (mass). A lighter car will achieve higher acceleration for the same amount of force.";
      }
      if (q.includes("newton's third law")) {
          return "Newton's Third Law states that for every action, there is an equal and opposite reaction. When the CO2 canister expels gas backward (action), the car is pushed forward (reaction). This is what propels our car down the track.";
      }
      if (q.includes('kinetic energy')) {
          return "Kinetic energy is the energy of motion, calculated as KE = 1/2 * m * v^2 (mass × velocity squared). The faster our car goes, the more kinetic energy it has. This energy must be safely dissipated by the braking system at the end of the track.";
      }
      if (q.includes('potential energy')) {
          return "Potential energy is stored energy. In the context of our track, it's mostly gravitational potential energy (PE = mgh). Since the track is flat, changes in potential energy are negligible, so we focus on converting the canister's chemical energy into kinetic energy as efficiently as possible.";
      }
      if (q.includes('momentum')) {
          return "Momentum (p = mv) is 'mass in motion'. A heavier car will have more momentum at the same speed. Understanding momentum is important for analyzing collisions and the stability of the car on the track.";
      }
      if (q.includes('friction')) {
          return "Friction is a force that opposes motion between surfaces in contact. For our car, we want to minimize friction from the wheels and axles on the track and guide line. This is why bearing quality and alignment are so important.";
      }
      if (q.includes('center of mass') || q.includes('centre of mass')) {
          return "The center of mass is the point where the entire mass of the car can be considered to be concentrated. A low center of mass is crucial for stability, preventing the car from tipping over, especially during the initial high-acceleration phase.";
      }
      if (q.includes('work') && q.includes('energy')) {
          return "The Work-Energy Theorem states that the work done on an object is equal to the change in its kinetic energy. The work done by the CO2 canister's thrust (minus the negative work done by drag and friction) determines the final kinetic energy, and thus the final speed, of our car.";
      }
      if (q.includes('power')) {
          return "Power is the rate at which work is done (P = W/t). A more powerful CO2 canister would release its energy more quickly, resulting in higher acceleration and a faster time, assuming the car can handle the forces.";
      }


      if (q.includes('team name')) {
          return "Team: Blizzard Racing. Mission: Win the F1 in Schools UK National Finals.";
      }
      if (q.includes('manager')) {
          const match = knowledge.match(/team manager: (.*)/);
          return match ? `Manager: ${match[1]}.` : "Manager's name not found in knowledge base.";
      }
      if (q.includes('goal') || q.includes('objective')) {
          const match = knowledge.match(/goal: (.*)/);
          return match ? `Primary Goal: ${match[1]}.` : "Goal not specified in knowledge base.";
      }
       if (q.includes('sponsor')) {
          const match = knowledge.match(/sponsors: (.*)/);
          return match ? `Sponsors: ${match[1]}.` : "Sponsorship info not available.";
      }
      if(q.includes('hello') || q.includes('hi')) {
        return "Icicle online. How can I help?";
      }

      return "Information not found in knowledge base. A manager can update it.";
  }
};